version: '3.8'

services: 
  development:
    build:
      context: .
      dockerfile: Dockerfile
  app:
    depends_on:
      - app_db
    image: ghcr.io/wp-graphql/wp-graphql:latest-wp6.3-php8.2
    volumes:
      - '..:/var/www/html/wp-content/plugins/wp-graphql'
      - '../.log/app:/var/log/apache2'
      - './mu-plugins:/var/www/html/wp-content/mu-plugins'
    env_file:
      - ../.env.dist
    environment:
      WP_URL: 'https://glowing-garbanzo-ppp696r94c7v47-8080.app.github.dev/'
      USING_XDEBUG: ${USING_XDEBUG:-}
      WP_DEBUG: 'true'
    ports:
      - 8080:80

  app_db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      wordpress
      MYSQL_USER:          wordpress
      MYSQL_PASSWORD:      wordpress
    ports:
      - 3306